apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.deployment.nameapp }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
       app: {{ .Values.deployment.nameapp }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.nameapp }}
    spec:
      containers:
      - image: igorferrati/nginx-igor
        name: nginx-igor
        