apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
     app: {{ .Values.deployment.nameapp }}
  ports:
  - port: 80
    targetPort: 80
